# Generated by Django 2.2.2 on 2020-01-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='slug',
            field=models.SlugField(default='gigil-gmail-com'),
            preserve_default=False,
        ),
    ]
