# Generated by Django 2.2.2 on 2020-01-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_userdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='weigh_photo',
            field=models.ImageField(upload_to='weight_photo'),
        ),
    ]
