# Generated by Django 2.2.2 on 2020-01-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20200107_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='weigh_photo',
            field=models.ImageField(blank=True, null=True, upload_to='weight_photo'),
        ),
    ]
