# Generated by Django 2.2.2 on 2020-01-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_auto_20200107_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='body_photo',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='weigh_photo',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='weight',
        ),
        migrations.CreateModel(
            name='MyFittness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigh_photo', models.ImageField(blank=True, null=True, upload_to='weight_photo')),
                ('body_photo', models.ImageField(blank=True, null=True, upload_to='body_photo')),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.UserDetails')),
            ],
        ),
    ]
